version: '3.8'

services:
  frontend:
    image: wallipot-app
    build: ../
    ports:
      - "8080:80"
    container_name: wallipot_frontend
    networks:
      - wallinet

  sonarqube:
    image: sonarqube:latest
    ports:
      - "9000:9000"
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:h2:tcp://localhost:9092/sonar
    networks:
      - wallinet

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    networks:
      - wallinet

networks:
  wallinet:

volumes:
  jenkins_home:
